Pages/Shopping/CheckOut.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Repositories;
using Dagli.Services;
using Dagli.Models;
using Dagli.Interfaces;
using Microsoft.AspNetCore.Http;

namespace Dagli.Pages.Shopping
{
    public class CheckOutModel : PageModel
    {
        
        private JsonOrderRepository repository;
        private ShoppingCartService cart;
        ILoginService userService;

        [BindProperty]
        public Login UserLogin { get; set; }
        public Order Order { get; set; }

        public string userName { get; set; }

        public List<Product> checkoutList { get; set; }

        public string totalPrice { get; set; }

        public CheckOutModel(JsonOrderRepository repo, ShoppingCartService cartService, ILoginService users)
        {
            repository = repo;
            cart = cartService;
            userService = users;
        }

        public void OnGet()
        {
            checkoutList = cart.GetOrderedProducts();
            totalPrice = cart.CalculateTotalPrice().ToString();

            userName = HttpContext.Session.GetString("UserName");

            List<Login> users = userService.GetLogins();

            if (HttpContext.Session.GetString("UserName") != null)
            {
                foreach (Login login in users)
                {
                    if (login.Email == userName)
                    {
                        UserLogin = login;
                    }
                }
            }
        }

        public IActionResult OnPostConfirm()
        {
            List<Login> users = userService.GetLogins();
            Order order = new Order();

            userName = HttpContext.Session.GetString("UserName");

            if (HttpContext.Session.GetString("UserName") != null)
            {
                foreach (Login login in users)
                {
                    if (login.Email == userName)
                    {
                        order.User = login;
                    }
                }
            }

            order.Products = cart.GetOrderedProducts();
            repository.AddOrder(order);
            cart.RemoveAllFromCart();
            return RedirectToPage("Confirmation");
        }

        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/Shopping/Confirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Http;

namespace Dagli.Pages.Shopping
{
    public class ConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/Shopping/ShoppingCart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Services;
using Dagli.Interfaces;
using Dagli.Models;
using Microsoft.AspNetCore.Http;

namespace Dagli.Pages.Shopping
{
    public class ShoppingCartModel : PageModel
    {
        public ShoppingCartService CartService { get; }
        public List<Product> ShoppingList { get; set; }
        private IProductRepository repo;
        [BindProperty]
        public Product Product { get; set; }

        public ShoppingCartModel(IProductRepository repository, ShoppingCartService cart)
        {
            repo = repository;
            CartService = cart;
            ShoppingList = new List<Product>();
        }

        public IActionResult OnGet(int id)
        {
            Product product = repo.GetProduct(id);
            ShoppingList = CartService.GetOrderedProducts();
            return Page();
        }

        public IActionResult OnPostReduceAmount(int id)
        {
            CartService.ReduceAmount(id);
            ShoppingList = CartService.GetOrderedProducts();
            return Page();
        }

        public IActionResult OnPostAddAmount(int id)
        {
            CartService.AddAmount(id);
            ShoppingList = CartService.GetOrderedProducts();
            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            CartService.RemoveProduct(id);
            ShoppingList = CartService.GetOrderedProducts();
            return Page();
        }

        public IActionResult OnPostCheckOut()
        {
            return Page();
        }
        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/Shopping/CheckOut.cshtml
@page
@model Dagli.Pages.Shopping.CheckOutModel
@{
    ViewData["Title"] = "Check Out";
}

@if (Model.validUser == 1)
{
<div class="row justify-content-center">
    <div class="col-auto">
        <table class="table table-responsive userTable">
            <thead>
                <tr>
                    <th class="text-center" colspan="2">Bruger Information</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">Email</th>
                    <td>@Model.UserLogin.Email</td>
                </tr>
                <tr>
                    <th scope="row">Navn</th>
                    <td>@Model.UserLogin.Name</td>
                </tr>
                <tr>
                    <th scope="row">Vej</th>
                    <td>@Model.UserLogin.Street</td>
                </tr>
                <tr>
                    <th scope="row">Postnummer</th>
                    <td>@Model.UserLogin.ZipCode</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
}
else
{
    <h2 class="pageTitle">Du skal være logget ind for at betale. Klik <a asp-page="/LoginService/LoginToSide">her</a> for at logge ind.</h2>
}
<h5>Indkøbskurv</h5>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Produkt</th>
            <th>Type</th>
            <th>Billede</th>
            <th>Antal</th>
            <th class="text-right">Pris</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Product item in Model.checkoutList)
        {
            <tr>
                <td class="text-left">@item.Name</td>
                <td class="text-left">@item.ProductType</td>
                <td><img src="~/Images/@item.ImageName" width="60" height="70"></td>
                <td class="text-left">@item.ProductAmount</td>
                <td class="text-right">@item.Price.ToString() kr</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total Pris:</td>
            <td class="text-right">
                @Model.totalPrice kr
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a asp-page="ShoppingCart" class="btn btn-primary">Tilbage til indkøbskurv</a>
    @if (Model.validUser == 1 && Model.checkoutList.Count > 0)
    {
        <div class="payButton">
            <form method="post">
                <button asp-page-handler="Confirm"
                        class="btn btn-primary">
                    Betal
                </button>
            </form>
        </div>
    }
</div>

Pages/Shopping/Confirmation.cshtml
@page
@model Dagli.Pages.Shopping.ConfirmationModel
@{
}
<h4>Din ordre er modtaget. Du vil modtage en email med ordrebekræftelse.</h4>

Pages/Shopping/ShoppingCart.cshtml
@page

@model Dagli.Pages.Shopping.ShoppingCartModel
@{
    ViewData["Title"] = "Indkøbskurv";
}
<h1 class="pageTitle">Indkøbskurv</h1>

@if (Model.ShoppingList != null && Model.ShoppingList.Count > 0)
{<h5>Mængden af produkter i din indkøbskurv er : @Model.ShoppingList.Count</h5>}
else
{ <h5>Ingen produkter i din indkøbskurv</h5>}

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Produkt</th>
            <th>Type</th>
            <th>Billede</th>
            <th>Antal</th>
            <th class="text-right">Pris Stk</th>
            <th class="text-right">Pris</th>
        </tr>
    </thead>
    @if (Model.ShoppingList.Count != 0)
    {
    <tbody>
        @foreach (Product item in Model.ShoppingList)
        {
        <tr>
            <td class="text-center">@item.Name</td>
            <td class="text-left">@item.ProductType</td>
            <td>
                <img src="~/Images/@item.ImageName" width="60" height="70">
            </td>
            <td class="text-center">
                <div class="float-right">
                    <form method="post">
                        <button asp-page-handler="AddAmount" asp-route-id="@item.ID"
                                class="btn btn-light btn-outline-success btn-group-lg float-right">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                            </svg>
                        </button>
                    </form>
                </div>
                @item.ProductAmount
                <div class="float-left">
                    <form method="post">
                        <button asp-page-handler="ReduceAmount" asp-route-id="@item.ID"
                                class="btn btn-light btn-outline-danger btn-group-lg float-right">
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" class="bi bi-dash-circle" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                                <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 0 1h-7A.5.5 0 0 1 4 8z" />
                            </svg>
                        </button>
                    </form>
                </div>
            </td>
            <td class="text-right">@item.Price.ToString() kr</td>
            <td class="text-right">
                @{var total = item.Price*item.ProductAmount;}
                        @total.ToString() kr
                    </td>
            <td>
                <form method="post">
                    <button asp-page-handler="Delete" asp-route-id="@item.ID"
                            class="btn btn-danger btn-group-lg pull-right">
                        Fjern fra kurv
                    </button>
                </form>
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5" class="text-right">Total price:</td>
            <td class="text-right">
                @Model.CartService.CalculateTotalPrice().ToString() kr
            </td>
        </tr>
    </tfoot>
    }
</table>
<div class="text-center">
    <a asp-page="/Products/AllProducts" class="btn btn-primary">Tilbage til produkter</a>
    @if (Model.ShoppingList.Count > 0)
    {
        <a asp-page="CheckOut" class="btn btn-primary">Bestil dine varer</a>
    }
</div>