Pages/LoginService/CreateUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Models;
using Dagli.Interfaces;
using Dagli.Services;
using Microsoft.AspNetCore.Http;

namespace Dagli.Pages.LoginService
{
    public class CreateUserModel : PageModel
    {
        ILoginService userService;
        public CreateUserModel(ILoginService service)
        {
            userService = service;
        }
        public Login login { get; set; }
        public string emailError { get; set; }
        public void OnPost()
        {
            List<Login> users = userService.GetLogins();

            if (ModelState.IsValid)
            {
                foreach (Login jsonUser in users)
                {
                    if (jsonUser.Email.ToLower() == Request.Form["Email".ToLower()])
                    {
                        emailError = "En bruger med denne email findes allerede";
                        return;
                    }
                }
            }
            Login user = new Login();
            user.Name = Request.Form["Navn"];
            user.Street = Request.Form["Vej"];
            user.ZipCode = Convert.ToInt32(Request.Form["Postnummer"]);
            user.Email = Request.Form["Email"];
            user.Password = Request.Form["Password"];

            userService.AddUser(user);
        }
        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/LoginService/LoginToSide.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Interfaces;
using Dagli.Models;
using Microsoft.AspNetCore.Http;
using Dagli.Pages.Products;


namespace Dagli.Pages.LoginService
{
    public class LoginToSideModel : PageModel
    {
        ILoginService userService;
        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
        public LoginToSideModel(ILoginService service)
        {
            userService = service;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            return CheckLogin();
        }

        public IActionResult OnPostLogOut()
        {
            return LogOut();
        }
        IActionResult CheckLogin()
        {
            string password;
            string userName;
            userName = Request.Form["Email"];
            password = Request.Form["Password"];
            bool checkLogin = userService.CheckPassword(userName, password);
            if (checkLogin == true)
            {
                if (userName == "admin@admin.dk")
                {
                    HttpContext.Session.SetInt32("Login", 1);
                    HttpContext.Session.SetString("UserName", userName);
                    HttpContext.Session.SetInt32("Admin", 1);
                    return Redirect("~/Products/AllProducts");
                }
                else
                {
                    HttpContext.Session.SetInt32("Login", 1);
                    HttpContext.Session.SetString("UserName", userName);
                    HttpContext.Session.SetInt32("Admin", 0);
                    return Redirect("~/Products/AllProducts");
                }
            }
            else
            {
                HttpContext.Session.SetInt32("Login", 0);
                HttpContext.Session.SetString("UserName", "");
                return Page();
            }
        }

        IActionResult LogOut()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("LoginToSide");
        }

    }
}

Pages/LoginService/CreateUser.cshtml
@page
@model Dagli.Pages.LoginService.CreateUserModel
@{
    ViewData["Title"] = "Opret Bruger";
}

@if (Model.emailError != null)
{
<div class="bg-danger">
    <h5>
        @Model.emailError
    </h5>
</div>
}

<div>
    <h5 class="pageTitle">Udfyld formular for at oprette en bruger</h5>
    <form method="post">
        Navn og efternavn:
        <br />
        <input name="Navn" type="text" class="form-control input-lg" required autofocus />
        <br />
        Vej og nr:
        <br />
        <input name="Vej" type="text" class="form-control input-lg" required />
        <br />
        Postnummer:
        <br />
        <input name="Postnummer" type="number" class="form-control input-lg" required />
        <br />
        E-Mail:
        <br />
        <input name="Email" type="email" class="form-control input-lg" required />
        <br />
        Kodeord:
        <br />
        <input name="Password" type="password" class="form-control input-lg" required />
        <br />
        <input id="SaveButton" type="submit" value="Opret Bruger" class="btn btn-primary">

        <a asp-page="LoginToSide" class="btn btn-primary">Log ind</a>
    </form>
</div>

Pages/LoginService/LoginToSide.cshtml
@page
@model Dagli.Pages.LoginService.LoginToSideModel
@{
    ViewData["Title"] = "LoginToSide";
}

@if (Model.validUser == 1)
{
    <p>Du er logget ind</p>
    <form method="post">
        <button asp-page-handler="LogOut"
                class="btn btn-dark btn-group-lg pull-right">
            Log ud
        </button>
    </form>
}
else
{
    <h1 class="pageTitle">Login</h1>
    <form method="post">
        E-Mail:
        <br />
        <input name="Email" type="email" class="form-control input-lg" required autofocus />
        <br />
        Password:
        <br />
        <input name="Password" type="password" class="form-control input-lg" required />
        <br />
        <input id="LoginButton" type="submit" value="Login" class="btn btn-success">
    </form>
}