Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Dagli
{
    public class Product
    {
        public int ID { get; set; }

        [Required]
        [StringLength(40, ErrorMessage = "Du skal have et navn, og det kan maks være 40 tegn.")]

        public string Name { get; set; }

        [Required(ErrorMessage = "Beskrivelse skal udfyldes, og kan maks fylde 150 tegn")]
        [StringLength(150)]
        public string Description { get; set; }

        [Required(ErrorMessage = "Price required")]
        [Range(typeof(decimal), "1", "10000",
        ErrorMessage = "Pris skal være mellem 1 og 10.000 kroner")]
        public decimal Price { get; set; }

        public string ImageName { get; set; }

        [Required(ErrorMessage = "Du skal vælge en produkt-type.")]

        public string ProductType { get; set; }
        public int ProductAmount { get; set; }

        public override string ToString()
        {
            return $"{ProductAmount} {Name} - {Price}";
        }
    }
}

Pages/Products/AllProducts.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Models;
using Dagli.Interfaces;
using Dagli.Services;
using Dagli.Pages.Shopping;
using Microsoft.AspNetCore.Http;

namespace Dagli.Pages.Products
{
    public class AllProductsModel : PageModel
    {
        private IProductRepository repository;
        [BindProperty]
        public Product Product { get; set; }
        public Dictionary<int, Product> Products { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Filter { get; set; }
        public List<Product> ShoppingList { get; set; }
        public ShoppingCartService CartService { get; }
        public AllProductsModel(IProductRepository repo, ShoppingCartService cart)
        {
            repository = repo;
            CartService = cart;
        }

        public IActionResult OnGet()
        {
            Products = repository.AllProducts();

            if (!string.IsNullOrEmpty(Filter))
            {
                Products = repository.FilterProduct(Filter);
            }
            return Page();
        }

        public IActionResult OnPostAddToCart(int id)
        {
            Product product = repository.GetProduct(id);
            CartService.Add(product);
            ShoppingList = CartService.GetOrderedProducts();
            Products = repository.AllProducts();
            return Page();
        }
        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/Products/CreateProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Models;
using Dagli.Interfaces;
using Microsoft.AspNetCore.Http;

namespace Dagli.Pages.Products
{
    public class CreateProductModel : PageModel
    {
        private IProductRepository repository;
        [BindProperty]
        public Product Product { get; set; }
        public Dictionary<int, Product> Products { get; set; }
        public CreateProductModel(IProductRepository repo)
        {
            repository = repo;
        }

        public void OnGet()
        {
            Products = repository.AllProducts();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            repository.AddProduct(Product);
            Products = repository.AllProducts();
            return RedirectToPage("AllProducts");
        }
        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/Products/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Models;
using Dagli.Interfaces;
using Microsoft.AspNetCore.Http;

namespace Dagli.Pages.Products
{
    public class EditProductModel : PageModel
    {
        private IProductRepository repository;
        [BindProperty]
        public Product Product { get; set; }
        public Dictionary<int, Product> Products { get; set; }
        public EditProductModel(IProductRepository repo)
        {
            repository = repo;
        }
        public IActionResult OnGet(int ID)
        {
            Product = repository.GetProduct(ID);
            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            repository.UpdateProduct(Product);
            return RedirectToPage("AllProducts");
        }
        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/Products/SingleProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Dagli.Models;
using Dagli.Interfaces;
using Microsoft.AspNetCore.Http;


namespace Dagli.Pages.Products
{
    public class SingleProductModel : PageModel
    {
        private IProductRepository repository;
        [BindProperty]
        public Product Product { get; set; }
        public Dictionary<int, Product> Products { get; set; }
        public SingleProductModel(IProductRepository repo)
        {
            repository = repo;
        }

        
        public List<string> Data { get; set; }

        public IActionResult OnGet(int ID)
        {
            Product = repository.GetProduct(ID);
            return Page();
        }

        public IActionResult OnPostDelete(int ID)
        {
            repository.DeleteProduct(ID);
            return RedirectToPage("AllProducts");
        }

        public int adminLogIn
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Admin")); }
        }
        public int validUser
        {
            get { return Convert.ToInt32(HttpContext.Session.GetInt32("Login")); }
        }
    }
}

Pages/Products/AllProducts.cshtml
@page
@model Dagli.Pages.Products.AllProductsModel
@{ ViewData["Title"] = "Alle Produkter";
}

<h1 class="pageTitle">Alle Produkter</h1>

@if (Model.Products != null && Model.Products.Count > 0)
{<h5>Mængden af produkter er : @Model.Products.Count</h5>}
else
{ <h5>Mængden af produkter er : 0</h5>}

@if (Model.adminLogIn == 1)
{
    <form>
        <button asp-page="CreateProduct"
                class="btn btn-primary">
            Tilføj Produkt
        </button>
    </form>
}
<br />
<form>
    <p>
        Filter varetype: <input type="text" asp-for="Filter" />
        <input type="submit" value="Filter" />
    </p>
</form>

<div class="grid">
    <div class="row">
        @foreach (Product item in Model.Products.Values)
        {
            <div class="productInGrid">
                <a asp-page="SingleProduct" asp-route-id="@item.ID"> <img class="img-thumbnail" src="~/Images/@item.ImageName"></a>

                <ul>
                    <li><a asp-page="SingleProduct" asp-route-id="@item.ID"><b>@item.Name</b></a></li>
                    <li style="font-size: 10px;">Varetype: @item.ProductType</li>
                    <li style="font-size: 10px;">Varenr. @item.ID</li>
                </ul>
                <form method="post">
                    <div class="button">
                        <label>
                            <input id="cartImg" type="image" src="~/Images/cart.svg"
                                   class="btn btn-success btn-group-lg"
                                   asp-page-handler="AddToCart" asp-route-id="@item.ID" />
                        </label>
                    </div>
                </form>
                <p>Pris <b>@item.Price</b> kr</p>
            </div>
        }
    </div>
</div>

Pages/Products/CreateProduct.cshtml
@page
@model Dagli.Pages.Products.CreateProductModel
@{
    ViewData["Title"] = "CreateProduct";
}
<style>
    h5 {
        text-align: center;
        color: blueviolet
    }
</style>

<h6 class="pageTitle">Lav et nyt produkt</h6>
<form class="form-horizontal" method="post">
    <div asp-validation-summary="ModelOnly"></div>

    <div class="form-group" style="width:25%">
        <label asp-for="@Model.Product.Name" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.Name" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.Name" class="text-danger"></span>
        </div>
    </div>
    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.Description" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.Description" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.Description" class="text-danger"></span>
        </div>
    </div>
    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.Price" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.Price" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.Price" class="text-danger"></span>
        </div>
    </div>

    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.ImageName" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.ImageName" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.ImageName" class="text-danger"></span>
        </div>
    </div>
    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.ProductType" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <select asp-for="@Model.Product.ProductType" class="form-control">
                <option>Diverse</option>
                <option>Frugt og grønt</option>
                <option>Drikkevarer</option>
                <option>Fisk og kød</option>
                <option>Frysevarer</option>
                <option>Hus og have</option>
            </select>
            <span asp-validation-for="@Model.Product.ProductType" class="text-danger"></span>
        </div>
    </div>
    

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="border-light">
                Add Product
            </button>
        </div>
    </div>
</form>

Pages/Products/EditProduct.cshtml
@page
@model Dagli.Pages.Products.EditProductModel
@{
}
<style>
    h5 {
        text-align: center;
        color: blueviolet
    }
</style>

<h6 class="pageTitle">Opdater produkt</h6>
<form class="form-horizontal" method="post">
    <div asp-validation-summary="ModelOnly"></div>

    <p>Varenummer er: @Model.Product.ID</p>

    <div class="form-group" style="width:25%">
        @*<label asp-for="@Model.Product.ID" class="control-label"></label>*@
            <input hidden="hidden" asp-for="@Model.Product.ID" class="form-control">
    </div>

    <div class="form-group" style="width:25%">
        <label asp-for="@Model.Product.Name" class="col-sm-2 control-label">Navn</label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.Name" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.Name" class="text-danger"></span>
        </div>
    </div>
    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.Description" class="col-sm-2 control-label">Beskrivelse</label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.Description" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.Description" class="text-danger"></span>
        </div>
    </div>
    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.Price" class="col-sm-2 control-label">Pris</label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.Price" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.Price" class="text-danger"></span>
        </div>
    </div>

    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.ImageName" class="col-sm-2 control-label">Billede</label>
        <div class="col-sm-10">
            <input asp-for="@Model.Product.ImageName" type="text" class="form-control">
            <span asp-validation-for="@Model.Product.ImageName" class="text-danger"></span>
        </div>
    </div>

    <div style="width:25%" class="form-group">
        <label asp-for="@Model.Product.ProductType" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <select asp-for="@Model.Product.ProductType" class="form-control">
                <option>Diverse</option>
                <option>Frugt og grønt</option>
                <option>Drikkevarer</option>
                <option>Fisk og kød</option>
                <option>Frysevarer</option>
                <option>Hus og have</option>
            </select>
            <span asp-validation-for="@Model.Product.ProductType" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">
                Edit product
            </button>
        </div>
    </div>
</form>

Pages/Products/SingleProduct.cshtml
@page "{ID}"
@model Dagli.Pages.Products.SingleProductModel
@{ ViewData["Title"] = "AllProducts";
}

<h1 class="pageTitle">@Model.Product.Name</h1>
<div class="productImage">
    <img src="~/Images/@Model.Product.ImageName">
</div>

<p>Beskrivelse: @Model.Product.Description</p>
<p>Pris: @Model.Product.Price</p>

@if (Model.adminLogIn == 1)
{
    <br>
    <br>
    <form method="post">
        <input type="submit"
               value="Edit"
               class="btn btn-primary"
               asp-page="EditProduct" asp-route-id="@Model.Product.ID" />
    </form>

    <br>
    <br>
    <form method="post">
        <input type="submit"
               value="Delete"
               class="btn btn-danger"
               asp-page-handler="Delete" asp-route-sessioncount="@Model.Product.ID"
               onclick="return confirm('Er du sikker på at du vil slette dette produkt?')" />
    </form>
}